application_api_version: v1beta1
properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  imageTelephonyBridge:
    type: string
    default: $REGISTRY:$TAG
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitByColon:
            before: imageWordpressRepo
            after: imageWordpressTag
  istioEnabled:
    type: boolean
    x-google-marketplace:
      type: ISTIO_ENABLED

required:
- name
- namespace
- imageTelephonyBridge
x-google-marketplace:
  clusterConstraints:
    resources:
    - replicas: 1
      requests:
        cpu: 1
      affinity:
        simpleNodeAffinity:
          type: REQUIRE_ONE_NODE_PER_REPLICA
    istio:
      type: OPTIONAL
    gcp:
      nodes:
        requiredOauthScopes:
        - https://www.googleapis.com/auth/cloud-platform
        - https://www.googleapis.com/auth/dialogflow
