apiVersion: v1
kind: Pod
metadata:
  name: "${name}-tester"
  labels:
    app.kubernetes.io/name: "${name}"
  annotations:
    marketplace.cloud.google.com/verification: test
spec:
  containers:
  - name: tester
    image: "${imageTester}"
    volumeMounts:
    - name: config-volume
      mountPath: /tester
    command: ["bash"]
    args: ["/tester/run.sh"]
  restartPolicy: Never
  volumes:
  - name: config-volume
    configMap:
      name: "${name}-test"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "${name}-test"
  labels:
    app.kubernetes.io/name: "${name}"
  annotations:
    marketplace.cloud.google.com/verification: test
data:
  run.sh: |-
    set -x
      echo SUCCESS
